from app.schemas import PaymentStatus

from typing import Dict, List, Any

PROCESSING_NETWORK_RULES: List[Dict[str, Any]] = [
    {"name": "Visa", "prefixes": ("4",), "ranges": [], "lengths": [13, 16]},
    {"name": "American Express", "prefixes": ('34', '37'), "ranges": [], "lengths": [15]},
    {"name": "Mastercard", "prefixes": ("51", "52", "53", "54", "55",), "ranges": [(2221, 2720)], "lengths": [16]},
    {"name": "Discover", "prefixes": (6011,), "ranges": [(644, 650)], "lengths": [16]}
]

NOTIFICATION_METHOD: Dict[PaymentStatus, str] = {
    PaymentStatus.FAILED: 'notify_failed_payment',
    PaymentStatus.SUCCEDED: "notify_successful_payment"
}

# NOTE: In test mode predefined Stripe tokens are used.
# In a real production environment the token must be generated by Stripe.js from the front-end.
# Additionally, a new field must be created in CardPaymentData to receive the token from the front-end.
STRIPE_TRIAL_TOKENS: Dict[str, str] = {
    "Visa": "tok_visa",
    "American Express": "tok_amex",
    "Mastercard": "tok_mastercard",
    "Discover": "tok_discover"
}